### ISSUE TITLE
[JOSS Review] Make it clear that the ROS 2 support is in the `wbc_ros` repository

### ISSUE THREAD

**Issue by sea-bass** [ARC-OPT/Documentation#3]
It took me a little while to figure out that the ROS 2 interface was available in a separate repository https://github.com/ARC-OPT/wbc_ros.

For new users, it may not be as easy to find that information, so I would recommend explicitly adding a link in this page: https://arc-opt.github.io/Documentation/tutorials/ros2_introduction.html

https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
Added a link to the documentation
