### ISSUE TITLE
[JOSS Review] Consider linking to the Python bindings examples in the docs

### ISSUE THREAD

**Issue by sea-bass** [ARC-OPT/Documentation#4]
It would be great to have another section that mentions the `wbc_py` Python bindings, and links to examples people can run if they're more comfortable with that vs. the core C++ or through ROS 2.

Minimally, there should be a section that at least links to the examples at https://github.com/ARC-OPT/wbc_py/tree/master/examples

https://github.com/openjournals/joss-reviews/issues/6696

**Comment by dmronga** [comment]
I updated the documentation to link to the python 3 examples
